platform :ios, '9.0'

target 'Tiki' do
  use_frameworks!
    pod 'SnapKit', '~>4.2.0'
    pod 'SDWebImage', '4.4.6'
    pod 'IQKeyboardManagerSwift'
    pod 'NVActivityIndicatorView'
    pod 'Alamofire', '4.8.1'
    pod 'SwiftyJSON', '~> 4.0'
    pod 'JGProgressHUD', '2.0.3'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'KeychainAccess', '4.2.1'
end
